"""
CREATE  A CLASS WITH A CLASS ATTRIBUTE A; CREATE AN OBJECT
FROM IT AND SET A DIRECTLY USING OBJECT.A=0. DOES THIS CHANGE THE CLASS ATTRIBUTE

ANSWER --> YES (PROOF IN THE BELOW CODE)
"""


class Object:
    a = 3


obj = Object()
obj.a = 32
print(obj.a)
