"""
CREATE A CLASS EMPLOYEE AND ADD SALARY AND INCREMENT PROPERTIES TO IT.
WRITE A METHOD SALARY  AFTER INCREMENT METHOD WITH A @ PROPERTY DECORATOR WITH A SETTER WHICH CHANGES THE VALUE OF
INCREMENT BASED ON THE SALARY
"""
